apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    volumeMounts:
    - name: test-nfs
      mountPath: /tmp/busybox
    command: ["/bin/sh","-c"]
    args: ["sleep 8888"]
  volumes:
  - name: test-nfs
    nfs:
      path: /data/k8s-nfs
      server: 192.168.0.11
      readOnly: true
