apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitor
  labels:
    application: "node-exporter"
spec:
  selector:
    prometheus: node-exporter
  type: NodePort
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
    nodePort: 39100
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitor
spec:
  selector:
    matchLabels:
     prometheus: node-exporter
  template:
    metadata:
      labels:
        prometheus: node-exporter
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.3.0
        ports:
        - containerPort: 9100
        resources:
          requests:
            cpu: 0.15 
        securityContext:
          privileged: true
        args:
        - --path.procfs=/host/proc 
        - --path.sysfs=/host/sys  
        - --path.rootfs=/host
        - --collector.systemd
        - --collector.processes
        volumeMounts:
        - name: dev
          mountPath: /host/dev
          readOnly: true
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: rootfs
          mountPath: /host
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: dev
        hostPath:
          path: /dev
      - name: sys
        hostPath:
          path: /sys
      - name: rootfs
        hostPath:
          path: /
