---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-data
  namespace: monitor
spec:
  accessModes: ["ReadWriteOnce"]
  capacity:
    storage: 10Gi
  nfs: 
    server: 192.168.0.10
    path: /data/prometheus
