apiVersion: v1
kind: Service
metadata:
  name: prometheus-pushgateway
  namespace: kube-prometheus
spec:
  selector: 
    name: prometheus-pushgateway 
  type: NodePort
  ports:
  - port: 9091
    targetPort: 9091
    nodePort: 42000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pushgateway
  namespace: kube-prometheus
  labels:
    name: prometheus-pushgateway 
spec:
  selector:
    matchLabels:
      name: prometheus-pushgateway 
  template:
    metadata:
      labels:
        name: prometheus-pushgateway 
    spec:
      nodeName: k8s-node-1                      # 指定在Work节点运行
      hostNetwork: true                         # 将容器端口在宿主机内暴露出来
      containers:
      - name: pushgateway
        image: prom/pushgateway:v1.4.2
        ports:
          - containerPort: 9091
