apiVersion: v1
kind: Service
metadata:
  name: cluster-nginx
  namespace: default
spec:
  selector:
    cluster-nginx: "true" 
  type: ClusterIP
  clusterIP: 10.0.0.254
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-nginx
  namespace: default
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster-nginx: "true"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: cluster-nginx
      labels:
        cluster-nginx: "true"
        app: "nginx"
    spec:
      restartPolicy: Always
      serviceAccountName: default
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
