---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: monitor
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: monitor
spec:
  serviceName: nginx
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: network-multitool
  namespace: monitor
spec:
  nodeName: k8s-master-1
  containers:
  - name: network-multitool
    image: praqma/network-multitool:latest
    command: ["/bin/sh","-c","sleep 10000"]
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: monitor
spec:
  nodeName: k8s-master-1
  containers:
  - name: alpine
    image: alpine:3.17.2
    command: ["/bin/sh","-c","sleep 10000"]
    imagePullPolicy: IfNotPresent
