apiVersion: v1
kind: Pod
metadata:
  labels:
    app: lvscare-lb
  name: lvscare-lb
spec:
  nodeName: k8s-node-1
  containers:
  - args:
    - care
    - --health-schem
    - http
    - --vs
    - 192.168.0.11:40005
    - --rs
    - 192.168.0.10:40003
    command:
    - /usr/bin/lvscare
    image: fanux/lvscare:latest
    imagePullPolicy: IfNotPresent
    name: lvscare
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 1
        memory: 1Gi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules
