apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-hostpath-sc
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: web-server
spec:
  conatainers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx
    persistentVolumeClaim: pv-volume
