apiVersion: v1
kind: Namespace
metadata:
  name: circuit-break
---
apiVersion: v1
kind: Service
metadata:
  name: busybox-httpd
  namespace: circuit-break
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: httpd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-httpd
  namespace: circuit-break
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: busybox-httpd
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 80
        command: ["/bin/sh","-c","echo 'this is busybox-httpd' > /var/www/index.html;httpd -f -h /var/www"]
