apiVersion: v1
kind: Namespace
metadata:
  name: ing-internal
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pong
  namespace: ing-internal
spec:
  rules:
    http:
      paths:
      - backend: 
          service:
            name: hi
            port:
              number: 5678
        path: /hi
        pathType: Prefix
