apiVersion: v1
kind: Pod
metadata:
  name: busybox-service-account
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    command:
    - "sleep"
    - "86400"
