apiVersion: v1
kind: Namespace
metadata:
  name: istio-inject
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: istio-inject
spec:
  selector:
    matchLabels:
      app: "nginx"
  template:
    metadata:
      labels:
        app: "nginx"
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      - name: busybox
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command: ["sh","-c","sleep 3600000"]
