apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-04-17T12:23:20Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2022-04-17T12:23:20Z"
  name: nginx
  namespace: istio-inject
  resourceVersion: "806644"
  uid: 66c6e512-7113-464d-a460-cc01d7e8d9c0
spec:
  clusterIP: 10.0.151.39
  clusterIPs:
  - 10.0.151.39
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
