apiVersion: v1
kind: Pod
metadata: 
  name: busybox
spec:
  restartPolicy: OnFailure
  imagePullSecrets:
  - name: aliyun-registry
  containers:
  - name: busybox
    image: registry.cn-hangzhou.aliyuncs.com/jiayu-kubernetes/busybox:1.28
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c","sleep 86400"]
