helm install elasticsearch -n logging \
--set image.debug=true,\
global.kibanaEnabled=true,\
master.masterOnly=true,\
master.replicaCount=1,\
master.heapSize=512m,\
master.nodeSelector."kubernetes\.io/hostname"=k8s-master-1,\
master.persistence.storageClass=local-elasticsearch-master,\
master.resources.limits.cpu=500m,\
master.resources.limits.memory=1Gi,\
master.resources.requests.cpu=25m,\
master.resources.requests.memory=256Mi,\
data.nodeSelector."kubernetes\.io/hostname"=k8s-master-1,\
data.persistence.storageClass=local-elasticsearch-data,\
data.replicaCount=1,\
data.heapSize=2148m,\
data.resources.limits.cpu=2,\
data.resources.limits.memory=4Gi,\
data.resources.requests.cpu=25m,\
data.resources.requests.memory=2Gi,\
coordinating.replicaCount=0,\
coordinating.resources.limits.cpu=500m,\
coordinating.resources.limits.memory=1Gi,\
coordinating.resources.requests.cpu=25m,\
coordinating.resources.requests.memory=256Mi,\
ingest.enabled=false,\
metrics.enabled=true,\
metrics.serviceMonitor.enabled=true,\
metrics.serviceMonitor.namespace=logging,\
kibana.persistence.storageClass=local-elasticsearch-kibana,\
kibana.nodeSelector."kubernetes\.io/hostname"=k8s-master-1 .
#master.persistence.enabled=false,\
#data.persistence.enabled=false,\
#kibana.persistence.enabled=false,\
