apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: monitor
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: monitor
subsets:
- addresses:
  - ip: 192.168.0.11
  - ip: 192.168.0.10
  ports:
  - port: 3306
