apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3306
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql   #默认创建service时就会生成一个与service名字一样的endpoints,并且会自动去关联
subsets:
- addresses:
  - ip: 192.168.0.11
  ports:
  - port: 3306
