apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx
  namespace: default
spec:
  exportTo:
  - "."
  hosts: # 由于跨了命名空间,所以fqdn
  - nginx-version-all.default.svc.cluster.local
  gateways:
  - mesh
  http:
  - match:
    route:
    - destination:
        host: nginx-version-all.default.svc.cluster.local
        port:
          number: 80
        subset: v1
      weight: 100
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: nginx
  namespace: default
spec:
  host: nginx-version-all.default.svc.cluster.local
  exportTo:
  - "*"
  subsets:
  - name: v1
    labels:
      app: nginx
      version: v1
