version: '3.1'
services:
  # zookeeper集群
  zookeeper:
    image: zookeeper:3.8.0
    container_name: zookeeper   # 容器名称
    restart: always             # 开机自启
    hostname: zookeeper         # 主机名
    #ports:
    #  - 2181:2181              # 端口号
    environment:
      ZOO_MY_ID: 1              # 每个节点不能一样
      ZOO_SERVERS: server.1=172.24.1.78:2888:3888;2181 server.2=172.24.1.238:2888:3888;2181 server.3=172.24.1.239:2888:3888;2181 # 填写集群IP即可
    network_mode: host
    volumes:
    - /etc/localtime:/etc/localtime
    - /data/zookeeper/data:/data
    - /data/zookeeper/datalog:/datalog
  # kafka集群
  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka
    restart: always             # 开机自启
    hostname: kafka
    #ports:
    #  - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1        # 每个节点不能一样   
      - KAFKA_ENABLE_KRAFT=no
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=172.24.1.78:2181,172.24.1.238:2181,172.24.1.239:2181   #连接zookeeper的服务地址
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.24.1.78:9092,EXTERNAL://172.24.1.78:9092  #填实际运行的机器IP
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
    network_mode: host
    volumes:
    - /etc/localtime:/etc/localtime
    - /data/kafka:/bitnami/kafka
    depends_on:
      - zookeeper
