apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http30
  namespace: default
#  annotations:
#    nginx.ingress.kubernetes.io/canary: "true"
#    nginx.ingress.kubernetes.io/canary-weight: "30"
spec:
  ingressClassName: nginx
  rules:
  - host: www.http.com
    http:
      paths:
      - backend:
          service:
            name: httpd-30
            port:
              name: http
        path: /
        pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http70
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "70"
spec:
  ingressClassName: nginx
  rules:
  - host: www.http.com
    http:
      paths:
      - backend:
          service:
            name: httpd-70
            port:
              name: http
        path: /
        pathType: Prefix
