apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests: 
      storage: 10Mi
---
apiVersion: v1
kind: Pod
medata:
  name: web-server
spec:
  containers:
  - name: web-server
    image: nginx
    volumeMounts: 
    - name: test
      mountPath: /usr/share/nginx/html
  volumes:
  - name: test
    persistentVolumeClaim:
      claimName: pv-volume
