---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx
  namespace: istio
spec:
  hosts:
  - nginx-version-all.default.svc.cluster.local
  gateways:
  - mesh
  tls:
  - match:
    - sniHosts:  # 将https流量直接透传给后端时需要配置这个域名
      - nginx-version-all.default.svc.cluster.local
      destinationSubnets:
      - "10.92.0.0/16" # 写了一个错误的svc
    route:
    - destination:
        host: nginx-version-all.default.svc.cluster.local
        port:
          number: 443
        subset: v1
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: nginx
  namespace: istio-system
spec:
  host: nginx-version-all.default.svc.cluster.local
  subsets:
  - name: v1
    labels:
      app: nginx
      version: v1
  - name: v2
    labels:
      app: nginx
      version: v2
