apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: logging
spec:    
  type: NodePort
  selector:
    application: kafka
  ports:
  - port: 9094
    targetPort: 9094
    nodePort: 39094
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: kafka
    namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kafka
  template:
    metadata:
      labels:
        application: kafka
    spec:
      nodeName: k8s-master-1
      containers:
      - name: "kafka"
        image: bitnami/kafka:3.3.1
        imagePullPolicy: IfNotPresent
        env:
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx1024m -Xms1024m"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_CFG_LISTENERS
          value: "INTERNAL://:9093,CLIENT://:9092,EXTERNAL://:9094"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "EXTERNAL://192.168.0.10:39094,INTERNAL://:9093,CLIENT://:9092"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "kafka-zookeeper:2181"
        ports:
        - name: external-port
          containerPort: 9094
        volumeMounts:
        - name: data
          mountPath: /bitnami/kafka
      volumes:
      - name: data
        hostPath:
          path: /data/kafka
