apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 20s 
      scrape_timeout: 10s
      evaluation_interval: 1m
    scrape_configs:
    - job_name: node-exporter
      static_configs:
      - targets: ['192.168.0.10:9100']
