apiVersion: v1
kind: Namespace
metadata:
  name: jms
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jms-config
  namespace: jms
data:
  MYSQL_DATABASE: "jumpserver"
  my.cnf: |
    [mysqld]
    basedir=/usr/
    datadir=/var/lib/mysql
    pid-file=/var/run/mysqld/mysqld.pid
    socket=/var/run/mysqld/mysqld.sock
    port=3306
    user=mysql
    log_error=/var/lib/mysql/mysql-error.log
    slow-query-log-file=/var/lib/mysql/mysql-slow.log
    log_bin=/var/lib/mysql/mysql-bin.log
    relay-log=/var/lib/mysql/mysql-relay-bin
    server-id=1
    innodb_buffer_pool_size=1024M
    innodb_log_buffer_size=16M
    key_buffer_size=128M
    query_cache_size=256M
    tmp_table_size=128M
    binlog_format=mixed 
    skip-external-locking
    skip-name-resolve
    character-set-server=utf8
    collation-server=utf8_bin
    max_allowed_packet=16M
    thread_cache_size=256
    table_open_cache=4096
    back_log=1024
    max_connect_errors=100000
    interactive_timeout=1800
    wait_timeout=1800
    max_connections=2048
    sort_buffer_size=16M
    join_buffer_size=4M
    read_buffer_size=4M
    read_rnd_buffer_size=16M
    binlog_cache_size=2M
    thread_stack=192K
    max_heap_table_size=128M
    myisam_sort_buffer_size=128M
    bulk_insert_buffer_size=256M
    open_files_limit=65535
    query_cache_limit=2M
    slow-query-log
    long_query_time=2
    expire_logs_days=3
    max_binlog_size=1000M
    slave_parallel_workers=4
    log-slave-updates
    binlog_ignore_db=mysql
    replicate_wild_ignore_table=mysql.%
    sync_binlog=1
    innodb_file_per_table=1
    innodb_flush_method=O_DIRECT
    innodb_buffer_pool_instances=4
    innodb_log_file_size=512M
    innodb_log_files_in_group=3
    innodb_open_files=4000
    innodb_read_io_threads=8
    innodb_write_io_threads=8
    innodb_thread_concurrency=8
    innodb_io_capacity=2000
    innodb_io_capacity_max=6000
    innodb_lru_scan_depth=2000
    innodb_max_dirty_pages_pct=85
    innodb_flush_log_at_trx_commit=2
    sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
    [mysqldump]
    quick
    quote-names
    max_allowed_packet=16M
    [client]
    default-character-set=utf8
    [mysql]
    default-character-set=utf8
    [isamchk]
    key_buffer=128M
    sort_buffer_size=4M
    read_buffer=2M
    write_buffer=2M
    [myisamchk]
    key_buffer=128M
    sort_buffer_size=4M
    read_buffer=2M
    write_buffer=2M
  redis.conf: |
    daemonize no
    bind 0.0.0.0
    port 6379
    timeout 300
    loglevel notice
    databases 16
    save 900 1
    save 300 10
    save 60 10000
    dbfilename dump.rdb
    rdbcompression yes
    dir /data
    loglevel warning
    logfile "/data/redis.log"
    maxclients 20480
    maxmemory 2g
    maxmemory-policy allkeys-lru
    appendonly no
    appendfilename "appendonly.aof"
    appendfsync no
  nginx.conf: |
    server {
      listen 80;
      client_max_body_size 4096m;
  
      location /ui/ {
        try_files $uri / /index.html;
        alias /opt/lina/;
      }
      
      location /luna/ {
        try_files $uri / /index.html;
        alias /opt/luna/;
      }
  
      location /download/ {
         alias /opt/download/;
      }
  
      location /media/replay/ {
        add_header Content-Encoding gzip;
        root /opt/jumpserver/data/;
      }
  
      location /media/ {
        root /opt/jumpserver/data/;
      }
  
      location /static/ {
        root /opt/jumpserver/data/;
      }
  
      location /koko/ {
        proxy_pass http://jms-koko.jms.svc.cluster.local:5000; 
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      location /lion/ {
          proxy_pass http://jms-lion.jms.svc.cluster.local:8081;
          proxy_buffering off;
          proxy_request_buffering off;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $http_connection;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_ignore_client_abort on;
          proxy_connect_timeout 600;
          proxy_send_timeout 600;
          proxy_read_timeout 600;
          send_timeout 6000;
      }
  
      # 企业版才有该功能
      #location /omnidb/ {
      #    resolver 127.0.0.11 valid=30s;
      #    set $upstream http://omnidb:8082;
      #    proxy_pass $upstream$request_uri;
      #    proxy_buffering off;
      #    proxy_http_version 1.1;
      #    proxy_set_header Upgrade $http_upgrade;
      #    proxy_set_header Connection $http_connection;
      #    proxy_set_header X-Real-IP $remote_addr;
      #    proxy_set_header Host $host;
      #    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      #}
  
      location /ws/ {
          proxy_pass http://jms-core.jms.svc.cluster.local:8070;
          proxy_buffering off;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
  
      location /api/ {
          proxy_pass http://jms-core.jms.svc.cluster.local:8080;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
  
      location /core/ {
          proxy_pass http://jms-core.jms.svc.cluster.local:8080;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }
  
      location / {
          rewrite ^/(.*)$ /ui/$1 last;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jms-core-config
  namespace: jms
data:
  SECRET_KEY: "ZWNjNzRkNTYtYWVmOS1jMjE3LWRlNmEtNDI0Zjk2ZWMxYzJk"
  BOOTSTRAP_TOKEN: "ZWNjNzRkNTYtYWVmOS1jMjE3"
  LOG_LEVEL: "ERROR"
  #  MySQL 配置, USE_EXTERNAL_MYSQL=1 表示使用外置 MySQL, 请输入正确的 MySQL 信息
  USE_EXTERNAL_MYSQL: "1"
  DB_HOST: "jms-mysql.jms.svc.cluster.local"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_PASSWORD: "jumpserver"
  DB_NAME: "jumpserver"
  ##  Redis 配置, USE_EXTERNAL_REDIS: 1 表示使用外置 Redis, 请输入正确的 Redis 信息
  USE_EXTERNAL_REDIS: "1"
  REDIS_HOST: "jms-redis.jms.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "jumpserver"
  # Nginx 配置
  HTTP_PORT: "80"
  SSH_PORT: "2222"
  RDP_PORT: "3389"
  # Task 配置, 是否启动 jms_celery 容器, 单节点必须开启
  USE_TASK: "1"
  # XPack, USE_XPACK: 1 表示开启, 开源版本设置无效
  USE_XPACK: "0"
  # Core 配置, Session 定义, SESSION_COOKIE_AGE 表示闲置多少秒后 session 过期, SESSION_EXPIRE_AT_BROWSER_CLOSE: true 表示关闭浏览器即 session 过期
  # SESSION_COOKIE_AGE: 86400
  SESSION_EXPIRE_AT_BROWSER_CLOSE: "true"
  # Koko Lion XRDP 组件配置
  CORE_HOST: "http://jms-core.jms.svc.cluster.local:8080"
  # Lion 开启字体平滑
  JUMPSERVER_ENABLE_FONT_SMOOTHING: "true"
  # Nginx 文件上传大小
  CLIENT_MAX_BODY_SIZE: "4096m"
  # 终端使用宿主 HOSTNAME 标识
  SERVER_HOSTNAME: "${HOSTNAME}"
  # 额外的配置
  CURRENT_VERSION: "v2.20.0"
