apiVersion: v1
kind: Secret
metadata:
  name: jms-secret
  namespace: jms
data:                  #密码：echo -n "jumpserver" | base64
  MYSQL_ROOT_PASSWORD: "anVtcHNlcnZlcg=="
  REDIS_PASSWORD: "anVtcHNlcnZlcg=="
---
