apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    volumeMounts:
    - name: test-directory
      mountPath: /tmp/busybox
    - name: test-file
      mountPath: /tmp/busybox/1.txt
    command: ["/bin/sh","-c"]
    args: ["sleep 8888"]
  volumes:
  - name: test-directory
    hostPath:
      type: DirectoryOrCreate
      path: /data
  - name: test-file
    hostPath:
      type: FileOrCreate
      path: /data/1.txt
