apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    volumeMounts:
    - name: test-file
      mountPath: /etc/test.txt
      subPath: 1.txt
    command: ["/bin/sh","-c"]
    args: ["sleep 8888"]
  volumes:
  - name: test-file
    hostPath:
      path: /data/
